### ISSUE TITLE
Docs TS: guide structural-directives

### ISSUE THREAD

**Issue by ocombe** [angular/angular-fr#29]
- [ ] structural-directives

**Comment by florianorpeliere** [comment]
Je prends :)

**Comment by manekinekko** [comment]
@florianorpeliere tu bosses tjrs sur cette tache ?

**Comment by florianorpeliere** [comment]
@manekinekko Oui, j'ai eu un peu de mal à trouver du temps, désolé. Je fais ma PR avant la fin de la semaine :)
